apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: roshan-harf-mcp

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: roshan-harf-mcp
    newTag: "0.1.0"
