apiVersion: v1
kind: Secret
metadata:
  name: roshan-harf-mcp
  namespace: roshan-harf-mcp
  labels:
    app.kubernetes.io/name: roshan-harf-mcp
type: Opaque
stringData:
  ROSHAN_HARF__INSTANCES__DEFAULT__USERNAME: "REPLACE_ME"
  ROSHAN_HARF__INSTANCES__DEFAULT__PASSWORD: "REPLACE_ME"
  # ROSHAN_HARF__INSTANCES__DEFAULT__TOKEN: "REPLACE_ME"
