apiVersion: v1
kind: Service
metadata:
  name: roshan-harf-mcp
  namespace: roshan-harf-mcp
  labels:
    app.kubernetes.io/name: roshan-harf-mcp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: roshan-harf-mcp
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
